//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.15 at 05:19:31 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.wfmc.org/2004/XPDL2.0alpha", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.truba.cp.bean.v20;
